Tracker:AddLocations("locations/Aridia.json")
Tracker:AddLocations("locations/Batalia.json")
Tracker:AddLocations("locations/Blarg.json")
Tracker:AddLocations("locations/Drek's Fleet.json")
Tracker:AddLocations("locations/Eudora.json")
Tracker:AddLocations("locations/Gaspar.json")
Tracker:AddLocations("locations/Gemlik.json")
Tracker:AddLocations("locations/Hoven.json")
Tracker:AddLocations("locations/Kalebo III.json")
Tracker:AddLocations("locations/Kerwan.json")
Tracker:AddLocations("locations/Novalis.json")
Tracker:AddLocations("locations/Oltanis.json")
Tracker:AddLocations("locations/Orxon.json")
Tracker:AddLocations("locations/Pokitaru.json")
Tracker:AddLocations("locations/Quartu.json")
Tracker:AddLocations("locations/Rilgar.json")
Tracker:AddLocations("locations/Umbris.json")
Tracker:AddLocations("locations/Veldin.json")
Tracker:AddLocations("locations/Overworld.json")